# -*- coding: utf-8 -*-
"""Password Generator & Strength Checker App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gseJjLpdyjae9do80trkyWhp1JL-FstF
"""

import random
import string

def generate_password(length, use_upper, use_digits, use_symbols):
    chars = string.ascii_lowercase
    if use_upper:
        chars += string.ascii_uppercase
    if use_digits:
        chars += string.digits
    if use_symbols:
        chars += string.punctuation

    password = ''.join(random.choice(chars) for _ in range(length))
    return password

def check_strength(password):
    score = 0
    if any(c.islower() for c in password): score += 1
    if any(c.isupper() for c in password): score += 1
    if any(c.isdigit() for c in password): score += 1
    if any(c in string.punctuation for c in password): score += 1

    if len(password) >= 12 and score == 4:
        return "Strong"
    elif len(password) >= 8 and score >= 3:
        return "Medium"
    else:
        return "Weak"

def main():
    print("--- Password Generator ---")
    length = int(input("Enter desired password length: "))
    use_upper = input("Include uppercase letters? (y/n): ").lower() == 'y'
    use_digits = input("Include digits? (y/n): ").lower() == 'y'
    use_symbols = input("Include symbols? (y/n): ").lower() == 'y'

    password = generate_password(length, use_upper, use_digits, use_symbols)
    print("Generated password:", password)
    print("Password Strength:", check_strength(password))

if __name__ == "__main__":
    main()